# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    name: mvn-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Maven Test
        env:
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_JWT_EXPIRATION_IN_MS: ${{ secrets.APP_JWT_EXPIRATION_IN_MS }}
        run: mvn test -P dev
